name: Runner Test

on:
  push:
    branches:
      - main

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Print runner info
        run: |
          echo "GitHub self-hosted runner is working"
          hostname
          whoami
          pwd
